add checking

diff --git a/.github/workflows/on-demand.yml b/.github/workflows/on-demand.yml
--- a/.github/workflows/on-demand.yml
+++ b/.github/workflows/on-demand.yml
@@ -45,6 +45,18 @@ jobs:
       QUARTUS: ${{ inputs.quartus-project }}
       VIVADO: ${{ inputs.vivado-project }}
     steps:
+    - name: Check options
+      run: |
+        if [ -n "$QUARTUS" ] && [ -n "$VIVADO"]
+        then
+          echo "::error::Multiple projects selected"
+          exit 1
+        fi
+        if [ -z "$QUARTUS" ] && [ -z "$VIVADO"]
+        then
+          echo "::error::No project selected"
+          exit 1
+        fi
     - name: Do Output
       run: |
         echo "QUARTUS: $QUARTUS"
